#
####################################
# Site Configurations
####################################
#
title: Daniel Guo
description: Daniel Guo's Personal Website

#
####################################
# Page Settings
####################################
#
owner:
  name: Daniel Guo
  bio: CS Master's student at Columbia University on the ML track. Broadly interested in computer science and mathematics.

#
####################################
# Handles and Links
####################################
#
links:
  email: danielguodev@gmail.com
  github: https://github.com/d-guo/
  linkedin: https://www.linkedin.com/in/dguo/
  telegram:
  twitter:
  blog: blog/

#
####################################
# Timeline
####################################
#
timeline:
  - job:
    company: Columbia University
    title: Master's in Computer Science
    start: Sep. 2022
    end:
    description: Machine Learning track

  - job:
    company: Atzberger Research Group
    title: Undergraduate Researcher
    start: Oct. 2018
    end:
    description: Data-efficient methods for inverse problems

  - job:
    company: Meta
    title: SWE Intern
    start: June 2022
    end: Sep. 2022
    description: Facebook Stories Contextual Replies team

  - job:
    company: Tesla
    title: SWE Intern
    start: Jan. 2022
    end: June 2022
    description: System Validation team
  
  - job:
    company: SB Hacks
    title: Director
    start: Mar. 2020
    end: Jan. 2022
    description: Organized UCSB's annual hackathon in 2021 and 2022

  - job:
    company: UC Santa Barbara
    title: Bachelor's in Computer Science and Mathematics
    start: Sep. 2018
    end: Dec. 2021
    description: College of Creative Studies

  - job:
    company: Visa
    title: SWE Intern
    start: June 2021
    end: Sep. 2021
    description: Visa Secure Downstream team

  - job:
    company: Semiotic AI
    title: R&D Intern
    start: June 2020
    end: Sep. 2020
    description: Privacy in ML models using fully homomorphic encryption

  - job:
    company: California Hospital
    title: Newborn
    start:
    end: 2000
    description: Birth
    